set MATLAB=C:\Program Files\MATLAB\R2015b
"%MATLAB%\bin\win64\gmake" -f BSC.mk optimized_floating_point=1 INCLUDE_MDL_TERMINATE_FCN=0 MAT_FILE=0 GENERATE_ASAP2=0 EXT_MODE=0 EXTMODE_STATIC_ALLOC=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 EXTMODE_TRANSPORT=0 TMW_EXTMODE_TESTING=0 MAX_DD_LENGTH=31 CONT_IF_VISION_STRATEGY_FAILS=0 ISPROTECTINGMODEL=NOTPROTECTING OPTS="-DSLMSG_ALLOW_SYSTEM_ALLOC"
