% Autogenerated file: Wed Apr 14 09:37:15 2021
function writeCodeInfoFcn


% Load a ComponentInterface object from IR
codeIRInfoStruct = load('D:\Projects\BMS\P006n\08_Work_in_progress\Repo_Sync_folder\HiLCAN\slprj\openecu_ert\BSC\tmwinternal\tlc\codeIRInfo.mat');
codeInfo = codeIRInfoStruct.codeInfo;



          
% Built-In Type: 8
 Type_8_R0_V0 = numerictype('boolean');
  Type_8_R0_V0.Name = 'boolean';
  Type_8_R0_V0.Identifier = 'boolean_T';
  Type_8_R0_V0.ReadOnly   = 0;
  Type_8_R0_V0.Volatile   = 0;
        
% Variable: Var_EO0
Var_EO0 = RTW.Variable(Type_8_R0_V0, 'bsc_CVTN_supply_signal');
    Var_EO0.Owner           = '';
    Var_EO0.DeclarationFile = '';
    
        
    % Setting Outport#1's Implementation    
    codeInfo.Outports(1).Implementation = Var_EO0;
    
% Variable: Var_EO1
Var_EO1 = RTW.Variable(Type_8_R0_V0, 'bsc_main_cc_cmd');
    Var_EO1.Owner           = '';
    Var_EO1.DeclarationFile = '';
    
        
    % Setting Outport#2's Implementation    
    codeInfo.Outports(2).Implementation = Var_EO1;
    
% Variable: Var_EO2
Var_EO2 = RTW.Variable(Type_8_R0_V0, 'bsc_chg_cc_cmd');
    Var_EO2.Owner           = '';
    Var_EO2.DeclarationFile = '';
    
        
    % Setting Outport#3's Implementation    
    codeInfo.Outports(3).Implementation = Var_EO2;
    
% Variable: Var_EO3
Var_EO3 = RTW.Variable(Type_8_R0_V0, 'bsc_sleep_status');
    Var_EO3.Owner           = '';
    Var_EO3.DeclarationFile = '';
    
        
    % Setting Outport#4's Implementation    
    codeInfo.Outports(4).Implementation = Var_EO3;
          
% Built-In Type: 3
Type_3_R0_V0 = numerictype(0, 8, 0);
  Type_3_R0_V0.Name = 'uint8';
  Type_3_R0_V0.Identifier = 'uint8_T';
  Type_3_R0_V0.ReadOnly   = 0;
  Type_3_R0_V0.Volatile   = 0;
        
% Variable: Var_EO4
Var_EO4 = RTW.Variable(Type_3_R0_V0, 'bsc_reason_to_open_CAN');
    Var_EO4.Owner           = '';
    Var_EO4.DeclarationFile = '';
    
        
    % Setting Outport#5's Implementation    
    codeInfo.Outports(5).Implementation = Var_EO4;
    
% Variable: Var_EO5
Var_EO5 = RTW.Variable(Type_3_R0_V0, 'bsc_severemed_fault');
    Var_EO5.Owner           = '';
    Var_EO5.DeclarationFile = '';
    
        
    % Setting Outport#6's Implementation    
    codeInfo.Outports(6).Implementation = Var_EO5;
    
% Variable: Var_EO6
Var_EO6 = RTW.Variable(Type_3_R0_V0, 'bsc_low_fault');
    Var_EO6.Owner           = '';
    Var_EO6.DeclarationFile = '';
    
        
    % Setting Outport#7's Implementation    
    codeInfo.Outports(7).Implementation = Var_EO6;
    
% Variable: Var_EO7
Var_EO7 = RTW.Variable(Type_3_R0_V0, 'bsc_fault_type');
    Var_EO7.Owner           = '';
    Var_EO7.DeclarationFile = '';
    
        
    % Setting Outport#8's Implementation    
    codeInfo.Outports(8).Implementation = Var_EO7;

skippedParameters = [];
      checkDataGraphicalNames(codeInfo.Parameters(1).GraphicalName, 'bscv_LowFaultType');


    
    % Setting Parameter#1's implementation  
    codeInfo.Parameters(1).Implementation = [];
      checkDataGraphicalNames(codeInfo.Parameters(2).GraphicalName, 'bscv_MediumFaultType');


    
    % Setting Parameter#2's implementation  
    codeInfo.Parameters(2).Implementation = [];
      checkDataGraphicalNames(codeInfo.Parameters(3).GraphicalName, 'bscv_SevereFaultType');


    
    % Setting Parameter#3's implementation  
    codeInfo.Parameters(3).Implementation = [];

  tmpParams = [];
if ~isempty(tmpParams)
codeInfo.Parameters = [codeInfo.Parameters; tmpParams];
end

          
  
  
  
  tmpArgs         = [];           
  tmpActualArgs   = [];           
  tmpRet          = [];           
  tmpActualReturn = [];           
    
      
% Char type    
Type_char_R1_V0 = embedded.chartype;
    Type_char_R1_V0.Identifier = 'char_T';
    Type_char_R1_V0.ReadOnly = 1;
    Type_char_R1_V0.Volatile = 0;
    

% Pointer Type: Pointer to Type_char_R1_V0    
PtrType_char_R1_V0_0_0 = embedded.pointertype;
   PtrType_char_R1_V0_0_0.BaseType = Type_char_R1_V0;
    PtrType_char_R1_V0_0_0.ReadOnly = 0;
    PtrType_char_R1_V0_0_0.Volatile = 0;
    

% Pointer Type: Pointer to PtrType_char_R1_V0_0_0    
PtrPtrType_char_R1_V0_0_0_0_0 = embedded.pointertype;
   PtrPtrType_char_R1_V0_0_0_0_0.BaseType = PtrType_char_R1_V0_0_0;
    PtrPtrType_char_R1_V0_0_0_0_0.ReadOnly = 0;
    PtrPtrType_char_R1_V0_0_0_0_0.Volatile = 0;
    
      Arg_rt_errorStatus = RTW.Argument;
    Arg_rt_errorStatus.Type = PtrPtrType_char_R1_V0_0_0_0_0;
    Arg_rt_errorStatus.Name = 'rt_errorStatus';
    tmpArgs = [tmpArgs; Arg_rt_errorStatus];

      
    
% Variable: Var_rt_errorStatus
Var_rt_errorStatus = RTW.Variable(PtrPtrType_char_R1_V0_0_0_0_0, 'rt_errorStatus');
    Var_rt_errorStatus.Owner           = '';
    Var_rt_errorStatus.DeclarationFile = '';
    
    
% Data Interface: idata_rt_errorStatus
idata_rt_errorStatus = RTW.DataInterface('', 'rt_errorStatus', Var_rt_errorStatus, []);
    
    tmpActualArgs = [tmpActualArgs; idata_rt_errorStatus];


    
    
    
  
    
  
  
    
  
  canParamStartIdx = length(codeInfo.Parameters) - 0 + 1;
  
  
    
    
  
  
  
  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
      
    

  
      
    

  
      
    

  
      
    

  
      
    

  
      
    

  
      
    

  
      
    

 
  
  
  
  
  
  
      
% Opaque Data Type
type_RTModel  = embedded.opaquetype('RT_MODEL_BSC');
      

% Pointer Type: Pointer to type_RTModel    
Ptrtype_RTModel_1_0 = embedded.pointertype;
   Ptrtype_RTModel_1_0.BaseType = type_RTModel;
    Ptrtype_RTModel_1_0.ReadOnly = 1;
    Ptrtype_RTModel_1_0.Volatile = 0;
    
    Ptrtype_RTModel_1_0.ReadOnly = 1;
        Arg_rtm = RTW.Argument;
    Arg_rtm.Type = Ptrtype_RTModel_1_0;
    Arg_rtm.Name = 'BSC_M';
    tmpArgs = [tmpArgs; Arg_rtm];

        
    
% Variable: Var_RTModel
Var_RTModel = RTW.Variable(type_RTModel, 'RTModel');
    Var_RTModel.Owner           = '';
    Var_RTModel.DeclarationFile = '';
    
    
% Data Interface: idata_RTModel
idata_RTModel = RTW.DataInterface('', 'RTModel', Var_RTModel, []);
    
    tmpActualArgs = [tmpActualArgs; idata_RTModel];

  
  
  
  
   
          
% Opaque Data Type
type_localZCE  = embedded.opaquetype('rtZCE_BSC');
      

% Pointer Type: Pointer to type_localZCE    
Ptrtype_localZCE_0_0 = embedded.pointertype;
   Ptrtype_localZCE_0_0.BaseType = type_localZCE;
    Ptrtype_localZCE_0_0.ReadOnly = 0;
    Ptrtype_localZCE_0_0.Volatile = 0;
    
        Arg_localZCE = RTW.Argument;
    Arg_localZCE.Type = Ptrtype_localZCE_0_0;
    Arg_localZCE.Name = 'localZCE';
    tmpArgs = [tmpArgs; Arg_localZCE];

        
    
% Variable: Var_localZCE
Var_localZCE = RTW.Variable(type_localZCE, 'localZCE');
    Var_localZCE.Owner           = '';
    Var_localZCE.DeclarationFile = '';
    
    
% Data Interface: idata_localZCE
idata_localZCE = RTW.DataInterface('', 'localZCE', Var_localZCE, []);
    
    tmpActualArgs = [tmpActualArgs; idata_localZCE];



  
  
  
    
  
    RegistrationFcn_Prototype = RTW.CImplementation;   
  RegistrationFcn_Prototype.HeaderFile = ['BSC', '.h'];
    RegistrationFcn_Prototype.SourceFile = ['BSC', '.c'];
  
  RegistrationFcn_Prototype.Name = 'BSC_initialize';
  RegistrationFcn_Prototype.Arguments  = tmpArgs;
  RegistrationFcn_Prototype.Return     = tmpRet;

    RegistrationFcn_Interface = RTW.FunctionInterface;
  
  RegistrationFcn_Interface.Prototype    = RegistrationFcn_Prototype;
  RegistrationFcn_Interface.ActualArgs   = tmpActualArgs;
  RegistrationFcn_Interface.ActualReturn = tmpActualReturn;
  
  time_constant = codeInfo.TimingProperties(getIndexFromTimingInternalId(codeInfo.TimingInternalIds, -1));
      RegistrationFcn_Interface.Timing = time_constant;
      codeInfo.InitializeFunctions =  [codeInfo.InitializeFunctions; RegistrationFcn_Interface'];
  

      
      
    
    
    tmpArgs         = [];           
    tmpActualArgs   = [];           
    tmpRet          = [];           
    tmpActualReturn = [];           

    
      
  
  
    
  
    
  
  canParamStartIdx = length(codeInfo.Parameters) - 0 + 1;
  
  
    
    
                        
% Built-In Type: 3
Type_3_R1_V0 = numerictype(0, 8, 0);
  Type_3_R1_V0.Name = 'uint8';
  Type_3_R1_V0.Identifier = 'uint8_T';
  Type_3_R1_V0.ReadOnly   = 1;
  Type_3_R1_V0.Volatile   = 0;
    
% Pointer Type: Pointer to Type_3_R1_V0    
PtrType_3_R1_V0_0_0 = embedded.pointertype;
   PtrType_3_R1_V0_0_0.BaseType = Type_3_R1_V0;
    PtrType_3_R1_V0_0_0.ReadOnly = 0;
    PtrType_3_R1_V0_0_0.Volatile = 0;
    
    
    
      codeInfo.Inports(1).Implementation.Identifier = ['i_' codeInfo.Inports(1).Implementation.Identifier];
      
        Arg_ci0 = RTW.Argument;
    Arg_ci0.Type = PtrType_3_R1_V0_0_0;
    Arg_ci0.Name = 'rtu_vehicle_PSR';
    tmpArgs = [tmpArgs; Arg_ci0];

    tmpActualArgs = [tmpActualArgs; codeInfo.Inports(1)];

                  
    
      codeInfo.Inports(2).Implementation.Identifier = ['i_' codeInfo.Inports(2).Implementation.Identifier];
      
        Arg_ci1 = RTW.Argument;
    Arg_ci1.Type = PtrType_3_R1_V0_0_0;
    Arg_ci1.Name = 'rtu_charger_PSR';
    tmpArgs = [tmpArgs; Arg_ci1];

    tmpActualArgs = [tmpActualArgs; codeInfo.Inports(2)];

                  
    
      codeInfo.Inports(3).Implementation.Identifier = ['i_' codeInfo.Inports(3).Implementation.Identifier];
      
        Arg_ci2 = RTW.Argument;
    Arg_ci2.Type = PtrType_3_R1_V0_0_0;
    Arg_ci2.Name = 'rtu_key';
    tmpArgs = [tmpArgs; Arg_ci2];

    tmpActualArgs = [tmpActualArgs; codeInfo.Inports(3)];

                        
% Built-In Type: 0
Type_0_R1_V0 = numerictype('double');
  Type_0_R1_V0.Name = 'double';
  Type_0_R1_V0.Identifier = 'real_T';
  Type_0_R1_V0.ReadOnly   = 1;
  Type_0_R1_V0.Volatile   = 0;
    
% Pointer Type: Pointer to Type_0_R1_V0    
PtrType_0_R1_V0_0_0 = embedded.pointertype;
   PtrType_0_R1_V0_0_0.BaseType = Type_0_R1_V0;
    PtrType_0_R1_V0_0_0.ReadOnly = 0;
    PtrType_0_R1_V0_0_0.Volatile = 0;
    
    
    
      codeInfo.Inports(4).Implementation.Identifier = ['i_' codeInfo.Inports(4).Implementation.Identifier];
      
        Arg_ci3 = RTW.Argument;
    Arg_ci3.Type = PtrType_0_R1_V0_0_0;
    Arg_ci3.Name = 'rtu_soc_pack_actual';
    tmpArgs = [tmpArgs; Arg_ci3];

    tmpActualArgs = [tmpActualArgs; codeInfo.Inports(4)];

                  
    
      codeInfo.Inports(5).Implementation.Identifier = ['i_' codeInfo.Inports(5).Implementation.Identifier];
      
        Arg_ci4 = RTW.Argument;
    Arg_ci4.Type = PtrType_3_R1_V0_0_0;
    Arg_ci4.Name = 'rtu_high_level_faultType1';
    tmpArgs = [tmpArgs; Arg_ci4];

    tmpActualArgs = [tmpActualArgs; codeInfo.Inports(5)];

                  
    
      codeInfo.Inports(6).Implementation.Identifier = ['i_' codeInfo.Inports(6).Implementation.Identifier];
      
        Arg_ci5 = RTW.Argument;
    Arg_ci5.Type = PtrType_3_R1_V0_0_0;
    Arg_ci5.Name = 'rtu_medium_level_faultType2';
    tmpArgs = [tmpArgs; Arg_ci5];

    tmpActualArgs = [tmpActualArgs; codeInfo.Inports(6)];

                  
    
      codeInfo.Inports(7).Implementation.Identifier = ['i_' codeInfo.Inports(7).Implementation.Identifier];
      
        Arg_ci6 = RTW.Argument;
    Arg_ci6.Type = PtrType_3_R1_V0_0_0;
    Arg_ci6.Name = 'rtu_low_level_faultType3';
    tmpArgs = [tmpArgs; Arg_ci6];

    tmpActualArgs = [tmpActualArgs; codeInfo.Inports(7)];

                  
    
      codeInfo.Inports(8).Implementation.Identifier = ['i_' codeInfo.Inports(8).Implementation.Identifier];
      
        Arg_ci7 = RTW.Argument;
    Arg_ci7.Type = PtrType_3_R1_V0_0_0;
    Arg_ci7.Name = 'rtu_vitm_CellsTemperatureLowFau';
    tmpArgs = [tmpArgs; Arg_ci7];

    tmpActualArgs = [tmpActualArgs; codeInfo.Inports(8)];

                  
    
      codeInfo.Inports(9).Implementation.Identifier = ['i_' codeInfo.Inports(9).Implementation.Identifier];
      
        Arg_ci8 = RTW.Argument;
    Arg_ci8.Type = PtrType_3_R1_V0_0_0;
    Arg_ci8.Name = 'rtu_vitm_CellsTemperatureHighFa';
    tmpArgs = [tmpArgs; Arg_ci8];

    tmpActualArgs = [tmpActualArgs; codeInfo.Inports(9)];

                  
    
      codeInfo.Inports(10).Implementation.Identifier = ['i_' codeInfo.Inports(10).Implementation.Identifier];
      
        Arg_ci9 = RTW.Argument;
    Arg_ci9.Type = PtrType_3_R1_V0_0_0;
    Arg_ci9.Name = 'rtu_vitm_CellsVoltageLowFaultTy';
    tmpArgs = [tmpArgs; Arg_ci9];

    tmpActualArgs = [tmpActualArgs; codeInfo.Inports(10)];

                  
    
      codeInfo.Inports(11).Implementation.Identifier = ['i_' codeInfo.Inports(11).Implementation.Identifier];
      
        Arg_ci10 = RTW.Argument;
    Arg_ci10.Type = PtrType_3_R1_V0_0_0;
    Arg_ci10.Name = 'rtu_vitm_CellsVoltageHightFault';
    tmpArgs = [tmpArgs; Arg_ci10];

    tmpActualArgs = [tmpActualArgs; codeInfo.Inports(11)];

                  
    
      codeInfo.Inports(12).Implementation.Identifier = ['i_' codeInfo.Inports(12).Implementation.Identifier];
      
        Arg_ci11 = RTW.Argument;
    Arg_ci11.Type = PtrType_3_R1_V0_0_0;
    Arg_ci11.Name = 'rtu_vitm_PackVoltageFaultType8';
    tmpArgs = [tmpArgs; Arg_ci11];

    tmpActualArgs = [tmpActualArgs; codeInfo.Inports(12)];

                  
    
      codeInfo.Inports(13).Implementation.Identifier = ['i_' codeInfo.Inports(13).Implementation.Identifier];
      
        Arg_ci12 = RTW.Argument;
    Arg_ci12.Type = PtrType_3_R1_V0_0_0;
    Arg_ci12.Name = 'rtu_vitm_PackCurrentFaultType9';
    tmpArgs = [tmpArgs; Arg_ci12];

    tmpActualArgs = [tmpActualArgs; codeInfo.Inports(13)];

                  
    
      codeInfo.Inports(14).Implementation.Identifier = ['i_' codeInfo.Inports(14).Implementation.Identifier];
      
        Arg_ci13 = RTW.Argument;
    Arg_ci13.Type = PtrType_3_R1_V0_0_0;
    Arg_ci13.Name = 'rtu_vitm_HVILFaultType10';
    tmpArgs = [tmpArgs; Arg_ci13];

    tmpActualArgs = [tmpActualArgs; codeInfo.Inports(14)];

                  
    
      codeInfo.Inports(15).Implementation.Identifier = ['i_' codeInfo.Inports(15).Implementation.Identifier];
      
        Arg_ci14 = RTW.Argument;
    Arg_ci14.Type = PtrType_3_R1_V0_0_0;
    Arg_ci14.Name = 'rtu_cc_PrechargeFaultType11';
    tmpArgs = [tmpArgs; Arg_ci14];

    tmpActualArgs = [tmpActualArgs; codeInfo.Inports(15)];

                    % Pointer Type: Pointer to 'Type_8_R0_V0'    
Type_29_R0_V0 = embedded.pointertype;
  Type_29_R0_V0.BaseType = Type_8_R0_V0;
  Type_29_R0_V0.ReadOnly = 0; 
  Type_29_R0_V0.Volatile = 0;
        
      codeInfo.Outports(1).Implementation.Identifier = ['o_' codeInfo.Outports(1).Implementation.Identifier];
    
        Arg_co1 = RTW.Argument;
    Arg_co1.Type = Type_29_R0_V0;
    Arg_co1.Name = 'rty_bsc_CVTN_supply_signal';
    tmpArgs = [tmpArgs; Arg_co1];

    tmpActualArgs = [tmpActualArgs; codeInfo.Outports(1)];

                  
      codeInfo.Outports(2).Implementation.Identifier = ['o_' codeInfo.Outports(2).Implementation.Identifier];
    
        Arg_co2 = RTW.Argument;
    Arg_co2.Type = Type_29_R0_V0;
    Arg_co2.Name = 'rty_bsc_main_cc_cmd';
    tmpArgs = [tmpArgs; Arg_co2];

    tmpActualArgs = [tmpActualArgs; codeInfo.Outports(2)];

                  
      codeInfo.Outports(3).Implementation.Identifier = ['o_' codeInfo.Outports(3).Implementation.Identifier];
    
        Arg_co3 = RTW.Argument;
    Arg_co3.Type = Type_29_R0_V0;
    Arg_co3.Name = 'rty_bsc_chg_cc_cmd';
    tmpArgs = [tmpArgs; Arg_co3];

    tmpActualArgs = [tmpActualArgs; codeInfo.Outports(3)];

                  
      codeInfo.Outports(4).Implementation.Identifier = ['o_' codeInfo.Outports(4).Implementation.Identifier];
    
        Arg_co4 = RTW.Argument;
    Arg_co4.Type = Type_29_R0_V0;
    Arg_co4.Name = 'rty_bsc_sleep_status';
    tmpArgs = [tmpArgs; Arg_co4];

    tmpActualArgs = [tmpActualArgs; codeInfo.Outports(4)];

                    % Pointer Type: Pointer to 'Type_3_R0_V0'    
Type_27_R0_V0 = embedded.pointertype;
  Type_27_R0_V0.BaseType = Type_3_R0_V0;
  Type_27_R0_V0.ReadOnly = 0; 
  Type_27_R0_V0.Volatile = 0;
        
      codeInfo.Outports(5).Implementation.Identifier = ['o_' codeInfo.Outports(5).Implementation.Identifier];
    
        Arg_co5 = RTW.Argument;
    Arg_co5.Type = Type_27_R0_V0;
    Arg_co5.Name = 'rty_bsc_reason_to_open_CAN';
    tmpArgs = [tmpArgs; Arg_co5];

    tmpActualArgs = [tmpActualArgs; codeInfo.Outports(5)];

                  
      codeInfo.Outports(6).Implementation.Identifier = ['o_' codeInfo.Outports(6).Implementation.Identifier];
    
        Arg_co6 = RTW.Argument;
    Arg_co6.Type = Type_27_R0_V0;
    Arg_co6.Name = 'rty_bsc_severemed_fault';
    tmpArgs = [tmpArgs; Arg_co6];

    tmpActualArgs = [tmpActualArgs; codeInfo.Outports(6)];

                  
      codeInfo.Outports(7).Implementation.Identifier = ['o_' codeInfo.Outports(7).Implementation.Identifier];
    
        Arg_co7 = RTW.Argument;
    Arg_co7.Type = Type_27_R0_V0;
    Arg_co7.Name = 'rty_bsc_low_fault';
    tmpArgs = [tmpArgs; Arg_co7];

    tmpActualArgs = [tmpActualArgs; codeInfo.Outports(7)];

                  
      codeInfo.Outports(8).Implementation.Identifier = ['o_' codeInfo.Outports(8).Implementation.Identifier];
    
        Arg_co8 = RTW.Argument;
    Arg_co8.Type = Type_27_R0_V0;
    Arg_co8.Name = 'rty_bsc_fault_type';
    tmpArgs = [tmpArgs; Arg_co8];

    tmpActualArgs = [tmpActualArgs; codeInfo.Outports(8)];

                    
% Opaque Data Type
type_localB  = embedded.opaquetype('rtB_BSC');
      

% Pointer Type: Pointer to type_localB    
Ptrtype_localB_0_0 = embedded.pointertype;
   Ptrtype_localB_0_0.BaseType = type_localB;
    Ptrtype_localB_0_0.ReadOnly = 0;
    Ptrtype_localB_0_0.Volatile = 0;
    
        Arg_localB = RTW.Argument;
    Arg_localB.Type = Ptrtype_localB_0_0;
    Arg_localB.Name = 'localB';
    tmpArgs = [tmpArgs; Arg_localB];

        
    
% Variable: Var_localB
Var_localB = RTW.Variable(type_localB, 'localB');
    Var_localB.Owner           = '';
    Var_localB.DeclarationFile = '';
    
    
% Data Interface: idata_localB
idata_localB = RTW.DataInterface('', 'localB', Var_localB, []);
    
    tmpActualArgs = [tmpActualArgs; idata_localB];


                    
% Opaque Data Type
type_localDW  = embedded.opaquetype('rtDW_BSC');
      

% Pointer Type: Pointer to type_localDW    
Ptrtype_localDW_0_0 = embedded.pointertype;
   Ptrtype_localDW_0_0.BaseType = type_localDW;
    Ptrtype_localDW_0_0.ReadOnly = 0;
    Ptrtype_localDW_0_0.Volatile = 0;
    
        Arg_localDW = RTW.Argument;
    Arg_localDW.Type = Ptrtype_localDW_0_0;
    Arg_localDW.Name = 'localDW';
    tmpArgs = [tmpArgs; Arg_localDW];

        
    
% Variable: Var_localDW
Var_localDW = RTW.Variable(type_localDW, 'localDW');
    Var_localDW.Owner           = '';
    Var_localDW.DeclarationFile = '';
    
    
% Data Interface: idata_localDW
idata_localDW = RTW.DataInterface('', 'localDW', Var_localDW, []);
    
    tmpActualArgs = [tmpActualArgs; idata_localDW];


                      Arg_localZCE = RTW.Argument;
    Arg_localZCE.Type = Ptrtype_localZCE_0_0;
    Arg_localZCE.Name = 'localZCE';
    tmpArgs = [tmpArgs; Arg_localZCE];

        
    tmpActualArgs = [tmpActualArgs; idata_localZCE];


  
  
  
  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
      
    

  
      
    

  
      
    

  
      
    

  
      
    

  
      
    

  
      
    

  
      
    

 
  
   
  
  
  
  
  
  
  
  
  
  
      
    
      OutputUpdateFcn_Prototype = RTW.CImplementation;   
  OutputUpdateFcn_Prototype.HeaderFile = ['BSC', '.h'];
    OutputUpdateFcn_Prototype.SourceFile = ['BSC', '.c'];
  
  OutputUpdateFcn_Prototype.Name = 'BSC';
  OutputUpdateFcn_Prototype.Arguments  = tmpArgs;
  OutputUpdateFcn_Prototype.Return     = tmpRet;

    
      OutputUpdateFcn_Interface = RTW.FunctionInterface;
  
  OutputUpdateFcn_Interface.Prototype    = OutputUpdateFcn_Prototype;
  OutputUpdateFcn_Interface.ActualArgs   = tmpActualArgs;
  OutputUpdateFcn_Interface.ActualReturn = tmpActualReturn;
  
  time_0 = codeInfo.TimingProperties(getIndexFromTimingInternalId(codeInfo.TimingInternalIds, 0));
      OutputUpdateFcn_Interface.Timing = time_0;
      codeInfo.OutputFunctions =  [codeInfo.OutputFunctions; OutputUpdateFcn_Interface'];
  

      
    

    
        
    
    
    tmpArgs         = [];           
    tmpActualArgs   = [];           
    tmpRet          = [];           
    tmpActualReturn = [];           

    
      
  
  
    
  
    
  
  canParamStartIdx = length(codeInfo.Parameters) - 0 + 1;
  
  
    
    
                  
      codeInfo.Outports(8).Implementation.Identifier = ['o_' codeInfo.Outports(8).Implementation.Identifier];
    
        Arg_co8 = RTW.Argument;
    Arg_co8.Type = Type_27_R0_V0;
    Arg_co8.Name = 'rty_bsc_fault_type';
    tmpArgs = [tmpArgs; Arg_co8];

    tmpActualArgs = [tmpActualArgs; codeInfo.Outports(8)];

                      Arg_localB = RTW.Argument;
    Arg_localB.Type = Ptrtype_localB_0_0;
    Arg_localB.Name = 'localB';
    tmpArgs = [tmpArgs; Arg_localB];

        
    tmpActualArgs = [tmpActualArgs; idata_localB];


  
  
  
  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
          
    
    

  
      
    

  
      
    

  
      
    

  
      
    

  
      
    

  
      
    

  
      
    

  
      
    

 
  
   
  
  
  
  
  
  
  
  
  
  
      
    
      InitializeFcn_Prototype = RTW.CImplementation;   
  InitializeFcn_Prototype.HeaderFile = ['BSC', '.h'];
    InitializeFcn_Prototype.SourceFile = ['BSC', '.c'];
  
  InitializeFcn_Prototype.Name = 'BSC_Init';
  InitializeFcn_Prototype.Arguments  = tmpArgs;
  InitializeFcn_Prototype.Return     = tmpRet;

    
      InitializeFcn_Interface = RTW.FunctionInterface;
  
  InitializeFcn_Interface.Prototype    = InitializeFcn_Prototype;
  InitializeFcn_Interface.ActualArgs   = tmpActualArgs;
  InitializeFcn_Interface.ActualReturn = tmpActualReturn;
  
        time_constant = codeInfo.TimingProperties(getIndexFromTimingInternalId(codeInfo.TimingInternalIds, -1));
  InitializeFcn_Interface.Timing = time_constant;
  codeInfo.InitConditionsFunction = InitializeFcn_Interface;    

  

    
      
    
    
    
    


    

  


if ~isempty(skippedParameters)
codeInfo.Parameters(skippedParameters) = [];
end

codeInfo.InternalData = [codeInfo.InternalData; idata_RTModel];
codeInfo.InternalData(end+1) = idata_localB;
codeInfo.InternalData(end+1) = idata_localDW;
codeInfo.InternalData(end+1) = idata_localZCE;
codeInfo.InternalData(end+1) = idata_rt_errorStatus;

% Handling Right-Click Builds
ss = rtwprivate('getSourceSubsystemHandle',codeInfo.GraphicalPath);
% Check if Rt-Click build, then re-map SIDs
if ~isempty(ss) && rtwprivate('rtwattic','hasSIDMap')
   codeInfo = modifyCodeInfoForSubsystemBuild(ss, codeInfo);
end

  lookupTableArray = [];         
  if exist('expInports', 'var')
      save BSC_mr_codeInfo.mat codeInfo expInports;
  else
      save BSC_mr_codeInfo.mat codeInfo;
  end
returnVal = 1;

% End Function: writeCodeInfoFcn

function idx = getIndexFromTimingInternalId(internalIdVec, internalId)
 idx = find(internalIdVec == internalId);
 if (isempty(idx) || (length(idx) > 1))
    ciMsg = 'Time object cannot be empty'; 
    ciExc = MException('RTW:buildProcess:CodeInfoInternalError',ciMsg);
    throw(ciExc);
  end
% End Function: getIndexFromTimingInternalId

function checkDataGraphicalNames(ciName, rtwName)
  if (strcmp(ciName, rtwName) ~= 1)
    ciMsg = ['Name mismatch: ', ciName, ' and ', rtwName]; 
    ciExc = MException('RTW:buildProcess:CodeInfoInternalError',ciMsg);
    throw(ciExc);
  end
% End Function: checkDataGraphicalNames

function iData = getInternalDataByName(iDataVec, iDataName)
 iData = find(iDataVec, 'GraphicalName', iDataName);
 if (isempty(iData) || (length(iData) > 1))
    ciMsg = 'Internal Data object cannot be empty'; 
    ciExc = MException('RTW:buildProcess:CodeInfoInternalError',ciMsg);
    throw(ciExc);
  end
% End Function: getInternalDataByName

function iData = getInternalDataByVariableName(iDataVec, iDataVariableName)
 iData = [];
 for idxData = 1:numel(iDataVec)
    if strcmp(iDataVariableName, iDataVec(idxData).Implementation.VariableName)
       iData = iDataVec(idxData);
       break
    end
 end
 if isempty(iData)
    ciMsg = 'Internal Data object cannot be empty'; 
    ciExc = MException('RTW:buildProcess:CodeInfoInternalError',ciMsg);
    throw(ciExc);
  end
% End Function: getInternalDataByVariableName

function codeInfo = modifyCodeInfoForSubsystemBuild(ss, codeInfo)
    
% Extract Subsystem Build Map from AtticData
    Subsystem_Build_Mapping = rtwprivate('rtwattic','getSIDMap');

% Parameters
    for i = 1:length(codeInfo.Parameters)
        sid = codeInfo.Parameters(i).SID;        

        sid = Simulink.ID.getSubsystemBuildSID(sid,ss, Subsystem_Build_Mapping);
        codeInfo.Parameters(i).SID = sid;        
    end
    
% Data Stores
     for i = 1:length(codeInfo.DataStores)
         sid = codeInfo.DataStores(i).SID;         

         sid = Simulink.ID.getSubsystemBuildSID(sid,ss, Subsystem_Build_Mapping);
         codeInfo.DataStores(i).SID = sid;
     end
    
% Inports
    for i = 1:length(codeInfo.Inports)
        sid = codeInfo.Inports(i).SID;
        
        sid = Simulink.ID.getSubsystemBuildSID(sid,ss, Subsystem_Build_Mapping);
        codeInfo.Inports(i).SID = sid;
    end
    
% Outports
    for i = 1:length(codeInfo.Outports)
        sid = codeInfo.Outports(i).SID;
 
        sid = Simulink.ID.getSubsystemBuildSID(sid,ss, Subsystem_Build_Mapping);
        codeInfo.Outports(i).SID = sid;
    end    
   
